@php
    $value = fn (string $key, mixed $default = null) => data_get($values ?? [], $key, old($key, $default));
@endphp
<div class="dg-modal-body"><div class="dg-form-grid">
    <div class="dg-field"><label>Control code *</label><input class="form-control" name="control_code" value="{{ $value('control_code') }}" maxlength="80" pattern="[A-Za-z0-9][A-Za-z0-9._-]*" required placeholder="e.g. DG-DQ-001"><small>A stable reference. Use a new version instead of changing an approved code.</small></div>
    <div class="dg-field"><label>Version *</label><input class="form-control" name="version" value="{{ $value('version', '1.0') }}" maxlength="30" pattern="[A-Za-z0-9._-]+" required placeholder="1.0"></div>
    <div class="dg-field dg-field-wide"><label>Instrument title *</label><input class="form-control" name="title" value="{{ $value('title') }}" maxlength="240" required placeholder="Clear, accountable name for the policy, standard or control"></div>
    <div class="dg-field"><label>Governance domain *</label><select class="form-select" name="governance_domain" required><option value="">Select domain</option>@foreach($domains as $key => $label)<option value="{{ $key }}" @selected($value('governance_domain') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Instrument type *</label><select class="form-select" name="instrument_type" required>@foreach($instrumentTypes as $key => $label)<option value="{{ $key }}" @selected($value('instrument_type', 'control') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Accountability scope *</label><select class="form-select" name="scope_type" required data-scope-select>@foreach($scopeTypes as $key => $label)<option value="{{ $key }}" @selected($value('scope_type', 'enterprise') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field" data-scope-field="portfolio,think_tank"><label>Governing portfolio</label><select class="form-select" name="portfolio_id"><option value="">No portfolio assignment</option>@foreach($portfolios as $portfolio)<option value="{{ $portfolio->id }}" @selected((string) $value('portfolio_id') === (string) $portfolio->id)>{{ $portfolio->name }}</option>@endforeach</select><small>Required for portfolio-scoped instruments and for think-tank instruments maintained by a portfolio manager.</small></div>
    <div class="dg-field" data-scope-field="think_tank"><label>Think tank *</label><select class="form-select" name="think_tank_member_id"><option value="">Select think tank</option>@foreach($thinkTanks as $thinkTank)<option value="{{ $thinkTank->id }}" @selected((string) $value('think_tank_member_id') === (string) $thinkTank->id)>{{ $thinkTank->name }}@if($thinkTank->country) · {{ $thinkTank->country }}@endif</option>@endforeach</select></div>
    <div class="dg-field"><label>Accountable owner</label><select class="form-select" name="owner_user_id"><option value="">Assign before review</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) $value('owner_user_id') === (string) $user->id)>{{ $user->name }} · {{ $user->role?->name ?: str($user->user_type)->headline() }}</option>@endforeach</select><small>Accountable for authorization, resources and risk acceptance.</small></div>
    <div class="dg-field"><label>Operational data steward</label><select class="form-select" name="steward_user_id"><option value="">Assign before review</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) $value('steward_user_id') === (string) $user->id)>{{ $user->name }} · {{ $user->role?->name ?: str($user->user_type)->headline() }}</option>@endforeach</select><small>Responsible for day-to-day definition, quality and compliance.</small></div>
    <div class="dg-field"><label>Data classification *</label><select class="form-select" name="data_classification" required>@foreach($classifications as $key => $label)<option value="{{ $key }}" @selected($value('data_classification', 'internal') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Risk rating *</label><select class="form-select" name="risk_rating" required>@foreach($risks as $key => $label)<option value="{{ $key }}" @selected($value('risk_rating', 'moderate') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Implementation state *</label><select class="form-select" name="implementation_status" required>@foreach($implementationStatuses as $key => $label)<option value="{{ $key }}" @selected($value('implementation_status', 'not_started') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Review frequency *</label><select class="form-select" name="review_frequency" required>@foreach($frequencies as $key => $label)<option value="{{ $key }}" @selected($value('review_frequency', 'annual') === $key)>{{ $label }}</option>@endforeach</select></div>
    <div class="dg-field"><label>Effective date</label><input class="form-control" type="date" name="effective_date" value="{{ $value('effective_date') }}"><small>Required before approval.</small></div>
    <div class="dg-field"><label>Next review date</label><input class="form-control" type="date" name="next_review_date" value="{{ $value('next_review_date') }}"><small>Must be after the effective date.</small></div>
    <div class="dg-field dg-field-full"><label>Purpose, applicability and scope</label><textarea class="form-control" name="description" rows="3" maxlength="5000" placeholder="What data and processes does this instrument govern, who must comply, and what outcome does it protect?">{{ $value('description') }}</textarea></div>
    <div class="dg-field dg-field-full"><label>Mandatory governance requirements</label><textarea class="form-control" name="requirements" rows="6" maxlength="20000" placeholder="State testable obligations: owner actions, access rules, collection standards, retention, review, escalation and evidence requirements.">{{ $value('requirements') }}</textarea><small>Requirements are mandatory before the draft can be submitted for review.</small></div>
    <div class="dg-field dg-field-wide"><label>Validated repository evidence</label><select class="form-select" name="evidence_repository_item_id"><option value="">No evidence linked</option>@foreach($evidenceItems as $item)<option value="{{ $item->id }}" @selected((string) $value('evidence_repository_item_id') === (string) $item->id)>{{ $item->title }} · {{ str($item->document_type)->replace('_', ' ')->headline() }}</option>@endforeach</select><small>Only validated, active repository documents are offered.</small></div>
    <div class="dg-field dg-field-wide"><label>Evidence and assurance notes</label><textarea class="form-control" name="evidence_notes" rows="3" maxlength="5000" placeholder="Describe implementation evidence, control testing, residual gaps or repository linkage.">{{ $value('evidence_notes') }}</textarea></div>
</div></div>
