<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('attp_think_tank_vendor_user')) {
            return;
        }

        if (! Schema::hasColumn('attp_think_tank_vendor_user', 'can_manage_setup')) {
            Schema::table('attp_think_tank_vendor_user', function (Blueprint $table): void {
                $table->boolean('can_manage_setup')->default(false)->after('status');
            });
        }

        // Neither users.think_tank_member_id (staff affiliation) nor a
        // consortium member's vendor_user_id (institutional transfer payee)
        // proves supplier-directory membership. Remove only rows generated by
        // the original automatic backfill; invited_by protects explicit rows.
        $unsafePairs = DB::table('attp_think_tank_vendor_user as membership')
            ->whereNull('membership.invited_by')
            ->where(function ($query): void {
                $query->whereExists(function ($staff): void {
                    $staff->selectRaw('1')
                        ->from('users')
                        ->whereColumn('users.id', 'membership.vendor_user_id')
                        ->whereColumn('users.think_tank_member_id', 'membership.think_tank_member_id');
                })->orWhereExists(function ($payee): void {
                    $payee->selectRaw('1')
                        ->from('attp_consortium_think_tanks as member')
                        ->whereColumn('member.id', 'membership.think_tank_member_id')
                        ->whereColumn('member.vendor_user_id', 'membership.vendor_user_id');
                });
            })
            ->get([
                'membership.think_tank_member_id',
                'membership.vendor_user_id',
            ]);

        foreach ($unsafePairs as $pair) {
            DB::table('attp_think_tank_vendor_user')
                ->where('think_tank_member_id', $pair->think_tank_member_id)
                ->where('vendor_user_id', $pair->vendor_user_id)
                ->whereNull('invited_by')
                ->delete();
        }
    }

    public function down(): void
    {
        // Deliberately do not recreate unsafe self-supplier memberships.
    }
};
