@extends('emails.layouts.base')

@section('content')
    <h2 style="margin-bottom: 14px;">Treaty Proof-of-Service Notification</h2>

    @if ($isResend)
        <div class="alert alert-info">
            <strong>Resent Notice:</strong> This email was resent from the member state portal because legal confirmation is still pending.
        </div>
    @endif

    <p>
        AU Legal Directorate,
    </p>
    <p>
        Please review the submitted proof-of-service details below and validate each code before final completion.
    </p>

    <div class="info-list">
        <p style="margin: 0 0 8px 0;"><strong>Member State:</strong> {{ $memberStateName }}</p>
        <p style="margin: 0 0 8px 0;"><strong>Treaty Title:</strong> {{ $treaty->title }}</p>
        <p style="margin: 0;"><strong>Treaty Reference:</strong> {{ $treaty->reference_code ?: 'N/A' }}</p>
    </div>

    @if ($status->signed_service_code)
        <div style="border: 1px solid #dbeafe; background: #eff6ff; border-radius: 10px; padding: 16px; margin-bottom: 14px;">
            <p style="margin: 0 0 6px 0; color: #1e40af;"><strong>Signed Service Code</strong></p>
            <p style="margin: 0; font-family: 'Courier New', monospace; font-size: 22px; font-weight: 700; letter-spacing: 1px; color: #1e3a8a;">
                {{ $status->signed_service_code }}
            </p>
            @if ($status->signed_service_code_verified_at)
                <p style="margin: 8px 0 0 0; color: #065f46; font-size: 13px;">
                    Verified on {{ $status->signed_service_code_verified_at->format('d M Y, H:i') }}.
                </p>
            @else
                <p style="margin: 8px 0 0 0; color: #92400e; font-size: 13px;">
                    Pending legal confirmation.
                </p>
            @endif
        </div>
    @endif

    @if ($status->ratified_service_code)
        <div style="border: 1px solid #dcfce7; background: #f0fdf4; border-radius: 10px; padding: 16px; margin-bottom: 18px;">
            <p style="margin: 0 0 6px 0; color: #166534;"><strong>Ratified Service Code</strong></p>
            <p style="margin: 0; font-family: 'Courier New', monospace; font-size: 22px; font-weight: 700; letter-spacing: 1px; color: #14532d;">
                {{ $status->ratified_service_code }}
            </p>
            @if ($status->ratified_service_code_verified_at)
                <p style="margin: 8px 0 0 0; color: #065f46; font-size: 13px;">
                    Verified on {{ $status->ratified_service_code_verified_at->format('d M Y, H:i') }}.
                </p>
            @else
                <p style="margin: 8px 0 0 0; color: #92400e; font-size: 13px;">
                    Pending legal confirmation.
                </p>
            @endif
        </div>
    @endif

    <a href="{{ $reviewUrl }}" class="btn">Open Treaty Review</a>

    <div class="divider"></div>

    <p style="font-size: 14px; color: #6b7280;">
        This message was generated by the ATTP-Africa treaty workflow. Confirmation should be completed only after the codes match the submission records.
    </p>
@endsection
