@extends('layouts.app')

@section('title', 'Data Governance Framework')
@section('lean_admin_scripts', '1')

@push('styles')
    @include('me.data-governance.partials.styles')
@endpush

@section('content')
@php
    $preservedFilters = collect($filters)->except('control_id')->reject(fn ($value) => $value === null || $value === '')
        ->reject(fn ($value, $key) => ($key === 'lifecycle' && $value === 'active') || ($key === 'sort' && $value === 'risk') || ($key === 'per_page' && (int) $value === 25))->all();
    $controlUrl = fn ($control) => route('budget.me.rebuild.data-governance', array_merge($preservedFilters, ['control_id' => $control->id])).'#governance-detail';
    $initials = function ($name) {
        return str(collect(preg_split('/\s+/', trim((string) $name)))->filter()->take(2)->map(fn ($part) => mb_substr($part, 0, 1))->join(''))->upper();
    };
    $tone = fn ($value) => match ($value) {
        'approved', 'implemented', 'resolved', 'low', 'scheduled' => 'success',
        'under_review', 'in_progress', 'internal', 'public' => 'info',
        'draft', 'moderate', 'due_soon', 'risk_accepted', 'not_started' => 'warning',
        'critical', 'high', 'overdue', 'open', 'restricted' => 'danger',
        default => 'neutral',
    };
    $selectedReviewState = $selectedControl?->reviewState();
    $oldContext = old('form_context');
    $oldAction = $selectedControl?->actions?->firstWhere('id', old('action_id'));
@endphp

<div class="mel-governance">
    <header class="dg-header">
        <div class="dg-header-copy">
            <span class="dg-eyebrow">Monitoring, Evaluation and Learning</span>
            <h1>Data Governance Framework</h1>
            <p>Define who is accountable for ATTP data, how it is classified and protected, which controls apply, when those controls are reviewed, and how governance gaps are resolved.</p>
        </div>
        <div class="dg-header-side">
            <span class="dg-generated">Posture calculated {{ $generatedAt->format('d M Y, H:i') }}</span>
            <div class="dg-actions">
                <a class="dg-btn dg-btn-header" href="{{ route('budget.me.rebuild.knowledge-repository') }}">Evidence repository</a>
                <a class="dg-btn dg-btn-header" href="{{ route('budget.me.rebuild.data-governance.csv', $exportQuery) }}">Download CSV</a>
                <a class="dg-btn dg-btn-header" href="{{ route('budget.me.rebuild.data-governance.pdf', $exportQuery) }}">Download PDF</a>
                @if($canManage)<a class="dg-btn dg-btn-header dg-btn-solid" href="#governance-add" data-dg-open="governance-add">New instrument</a>@endif
            </div>
        </div>
    </header>

    @if(session('success'))<div class="dg-alert success" role="status"><span>OK</span><div><strong>Governance register updated</strong><p>{{ session('success') }}</p></div></div>@endif
    @if($errors->any())<div class="dg-alert danger" role="alert"><span>!</span><div><strong>The governance change could not be completed</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div>@endif

    <aside class="dg-guidance" aria-label="Data governance guidance">
        <span>RULE</span><div><strong>Approval makes an instrument authoritative and immutable</strong><p>Make changes through a new controlled version. Ownership, evidence, review dates and remediation actions remain visible so governance decisions can be independently traced.</p></div>
        <ol><li><b>1</b>Draft</li><li><b>2</b>Review</li><li><b>3</b>Approve</li><li><b>4</b>Implement</li><li><b>5</b>Review</li></ol>
    </aside>

    <section class="dg-metrics" aria-label="Data governance posture summary">
        <a class="dg-metric" style="--metric:#075c7a" href="{{ route('budget.me.rebuild.data-governance', $preservedFilters) }}"><span>Active instruments</span><strong>{{ number_format($metrics['active']) }}</strong><small>{{ number_format($metrics['controls']) }} records in selected scope</small></a>
        <a class="dg-metric" style="--metric:#187459" href="{{ route('budget.me.rebuild.data-governance', array_merge($preservedFilters, ['status' => 'approved'])) }}"><span>Authoritative</span><strong>{{ number_format($metrics['approval_rate'], 1) }}%</strong><small>{{ number_format($metrics['approved']) }} approved instruments</small></a>
        <a class="dg-metric" style="--metric:#3f8aa0" href="{{ route('budget.me.rebuild.data-governance', array_merge($preservedFilters, ['implementation' => 'implemented'])) }}"><span>Implemented</span><strong>{{ number_format($metrics['implementation_rate'], 1) }}%</strong><small>{{ number_format($metrics['implemented']) }} controls operating</small></a>
        <a class="dg-metric" style="--metric:#6b63a8" href="#governance-register"><span>Ownership coverage</span><strong>{{ number_format($metrics['ownership_rate'], 1) }}%</strong><small>Owner and steward both assigned</small></a>
        <a class="dg-metric" style="--metric:#b8791f" href="{{ route('budget.me.rebuild.data-governance', array_merge($preservedFilters, ['review_state' => 'overdue'])) }}"><span>Review attention</span><strong>{{ number_format($metrics['overdue_reviews']) }}</strong><small>{{ number_format($metrics['due_soon']) }} more due within 30 days</small></a>
        <a class="dg-metric" style="--metric:#ae4d49" href="{{ route('budget.me.rebuild.data-governance', array_merge($preservedFilters, ['action_state' => 'open'])) }}"><span>Open actions</span><strong>{{ number_format($metrics['open_actions']) }}</strong><small>{{ number_format($metrics['critical_high']) }} high or critical-risk instruments</small></a>
    </section>

    <details class="dg-panel dg-filter" @if($activeFilterCount > 0) open @endif>
        <summary class="dg-panel-head"><div><h2>Governance scope and action filters</h2><p>The posture cards, charts, register and exports all use the same selected scope.</p></div><div class="dg-summary-right"><span class="dg-badge">{{ $activeFilterCount }} active {{ str('filter')->plural($activeFilterCount) }}</span><span class="dg-chevron">⌄</span></div></summary>
        <div class="dg-panel-body"><form method="GET" action="{{ route('budget.me.rebuild.data-governance') }}" class="dg-filter-grid">
            <div class="dg-field dg-field-wide"><label for="dg-search">Search the governance register</label><input class="form-control" id="dg-search" type="search" name="q" value="{{ $filters['q'] }}" placeholder="Control code, title, requirement, owner or steward"><small>Search is case-insensitive and applied before pagination.</small></div>
            <div class="dg-field"><label for="dg-domain">Governance domain</label><select class="form-select" id="dg-domain" name="domain"><option value="">All domains</option>@foreach($domains as $key => $label)<option value="{{ $key }}" @selected($filters['domain'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-status">Lifecycle</label><select class="form-select" id="dg-status" name="status"><option value="">All lifecycle states</option>@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-implementation">Implementation</label><select class="form-select" id="dg-implementation" name="implementation"><option value="">All implementation states</option>@foreach($implementationStatuses as $key => $label)<option value="{{ $key }}" @selected($filters['implementation'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-risk">Risk rating</label><select class="form-select" id="dg-risk" name="risk"><option value="">All risks</option>@foreach($risks as $key => $label)<option value="{{ $key }}" @selected($filters['risk'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-classification">Data classification</label><select class="form-select" id="dg-classification" name="classification"><option value="">All classifications</option>@foreach($classifications as $key => $label)<option value="{{ $key }}" @selected($filters['classification'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-scope">Accountability scope</label><select class="form-select" id="dg-scope" name="scope_type"><option value="">All scopes</option>@foreach($scopeTypes as $key => $label)<option value="{{ $key }}" @selected($filters['scope_type'] === $key)>{{ $label }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-portfolio">Portfolio</label><select class="form-select" id="dg-portfolio" name="portfolio_id"><option value="">All portfolios</option>@foreach($portfolios as $portfolio)<option value="{{ $portfolio->id }}" @selected($filters['portfolio_id'] === (string) $portfolio->id)>{{ $portfolio->name }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-owner">Accountable owner</label><select class="form-select" id="dg-owner" name="owner_user_id"><option value="">All owners</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected($filters['owner_user_id'] === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
            <div class="dg-field"><label for="dg-review">Review timing</label><select class="form-select" id="dg-review" name="review_state"><option value="">All review states</option><option value="overdue" @selected($filters['review_state'] === 'overdue')>Overdue</option><option value="due_soon" @selected($filters['review_state'] === 'due_soon')>Due within 30 days</option><option value="scheduled" @selected($filters['review_state'] === 'scheduled')>Scheduled later</option><option value="unscheduled" @selected($filters['review_state'] === 'unscheduled')>No review scheduled</option></select></div>
            <div class="dg-field"><label for="dg-actions">Action queue</label><select class="form-select" id="dg-actions" name="action_state"><option value="">Any action state</option><option value="open" @selected($filters['action_state'] === 'open')>Has open actions</option><option value="overdue" @selected($filters['action_state'] === 'overdue')>Has overdue actions</option><option value="clear" @selected($filters['action_state'] === 'clear')>No open actions</option></select></div>
            <div class="dg-field"><label for="dg-lifecycle">Register records</label><select class="form-select" id="dg-lifecycle" name="lifecycle"><option value="active" @selected($filters['lifecycle'] === 'active')>Active instruments</option><option value="retired" @selected($filters['lifecycle'] === 'retired')>Retired instruments</option><option value="all" @selected($filters['lifecycle'] === 'all')>Active and retired</option></select></div>
            <div class="dg-field"><label for="dg-sort">Sort register</label><select class="form-select" id="dg-sort" name="sort"><option value="risk" @selected($filters['sort'] === 'risk')>Risk and lifecycle priority</option><option value="review" @selected($filters['sort'] === 'review')>Review date</option><option value="code" @selected($filters['sort'] === 'code')>Control code</option><option value="title" @selected($filters['sort'] === 'title')>Title</option><option value="newest" @selected($filters['sort'] === 'newest')>Recently created</option><option value="updated" @selected($filters['sort'] === 'updated')>Recently updated</option></select></div>
            <div class="dg-field"><label for="dg-page">Rows per page</label><select class="form-select" id="dg-page" name="per_page">@foreach([15,25,50,100] as $size)<option value="{{ $size }}" @selected($filters['per_page'] === $size)>{{ $size }} rows</option>@endforeach</select></div>
            <div class="dg-filter-actions"><p><strong>Governance tip:</strong> combine high risk, overdue review and open actions to produce the Secretariat’s immediate intervention list.</p><div class="dg-actions"><a class="dg-btn dg-btn-secondary" href="{{ route('budget.me.rebuild.data-governance') }}">Clear filters</a><button class="dg-btn dg-btn-primary" type="submit">Apply scope</button></div></div>
        </form></div>
    </details>

    <section class="dg-analytics" id="governance-analytics" aria-label="Data governance charts">
        <article class="dg-panel dg-chart-panel"><div class="dg-panel-head"><div><h2>Lifecycle authority</h2><p>Draft, review, approved and retired instrument distribution.</p></div><span class="dg-badge">{{ number_format($metrics['controls']) }} records</span></div><div id="dg-lifecycle-chart" class="dg-chart" role="img" aria-label="Donut chart of governance instruments by lifecycle"></div></article>
        <article class="dg-panel dg-chart-panel dg-chart-wide"><div class="dg-panel-head"><div><h2>Domain implementation coverage</h2><p>Registered versus implemented instruments across governance domains.</p></div><span class="dg-badge">{{ number_format(count($charts['domain'])) }} domains</span></div><div id="dg-domain-chart" class="dg-chart" role="img" aria-label="Governance domain implementation bar chart"></div></article>
        <article class="dg-panel dg-chart-panel"><div class="dg-panel-head"><div><h2>Risk exposure</h2><p>Instruments grouped by current inherent governance risk.</p></div><span class="dg-badge">Posture</span></div><div id="dg-risk-chart" class="dg-chart" role="img" aria-label="Governance risk distribution chart"></div></article>
    </section>

    <section class="dg-panel dg-register" id="governance-register" aria-labelledby="governance-register-title">
        <div class="dg-panel-head"><div><h2 id="governance-register-title">Controlled governance register</h2><p>{{ number_format($controls->total()) }} matching {{ str('instrument')->plural($controls->total()) }} · authoritative versions and remediation accountability in one register.</p></div><div class="dg-actions"><a class="dg-btn dg-btn-small dg-btn-secondary" href="{{ route('budget.me.rebuild.data-governance.csv', $exportQuery) }}">CSV</a><a class="dg-btn dg-btn-small dg-btn-secondary" href="{{ route('budget.me.rebuild.data-governance.pdf', $exportQuery) }}">PDF</a>@if($canManage)<a class="dg-btn dg-btn-small dg-btn-primary" href="#governance-add" data-dg-open="governance-add">New instrument</a>@endif</div></div>
        @if($controls->isNotEmpty())
            <div class="dg-table-wrap"><table class="dg-table"><thead><tr><th>Instrument</th><th>Domain and scope</th><th>Owner / steward</th><th>Risk and classification</th><th>Lifecycle</th><th>Implementation</th><th>Review control</th><th>Actions</th><th>Updated</th></tr></thead><tbody>
            @foreach($controls as $control)
                @php $reviewState = $control->reviewState(); @endphp
                <tr class="{{ $selectedControl && (string) $selectedControl->id === (string) $control->id ? 'selected' : '' }}" data-dg-row data-href="{{ $controlUrl($control) }}">
                    <td><a class="dg-code" href="{{ $controlUrl($control) }}">{{ $control->control_code }} <small>v{{ $control->version }}</small></a><strong class="dg-cell-strong">{{ $control->title }}</strong><span class="dg-cell-note">{{ $instrumentTypes[$control->instrument_type] ?? str($control->instrument_type)->headline() }}</span></td>
                    <td><strong class="dg-cell-strong">{{ $domains[$control->governance_domain] ?? str($control->governance_domain)->headline() }}</strong><span class="dg-cell-note">{{ $scopeTypes[$control->scope_type] ?? str($control->scope_type)->headline() }} · {{ $control->portfolio?->name ?: $control->thinkTank?->name ?: 'ATTP enterprise' }}</span></td>
                    <td><div class="dg-person"><span>{{ $initials($control->owner?->name ?: 'Unassigned') }}</span><div><strong>{{ $control->owner?->name ?: 'Owner required' }}</strong><small>Steward: {{ $control->steward?->name ?: 'Not assigned' }}</small></div></div></td>
                    <td><span class="dg-status {{ $tone($control->risk_rating) }}">{{ $risks[$control->risk_rating] ?? str($control->risk_rating)->headline() }} risk</span><span class="dg-status {{ $tone($control->data_classification) }}">{{ $classifications[$control->data_classification] ?? str($control->data_classification)->headline() }}</span></td>
                    <td><span class="dg-status {{ $tone($control->status) }}">{{ $statuses[$control->status] ?? str($control->status)->headline() }}</span><span class="dg-cell-note">{{ $control->approved_at ? 'Approved '.$control->approved_at->format('d M Y') : 'Not yet authoritative' }}</span></td>
                    <td><span class="dg-status {{ $tone($control->implementation_status) }}">{{ $implementationStatuses[$control->implementation_status] ?? str($control->implementation_status)->headline() }}</span></td>
                    <td><span class="dg-status {{ $tone($reviewState) }}">{{ str($reviewState)->replace('_', ' ')->headline() }}</span><span class="dg-cell-note">{{ $control->next_review_date?->format('d M Y') ?: 'Date required before review' }}</span></td>
                    <td><strong class="dg-cell-strong">{{ number_format($control->open_actions_count) }} open</strong><span class="dg-cell-note {{ $control->overdue_actions_count ? 'danger-text' : '' }}">{{ number_format($control->overdue_actions_count) }} overdue · {{ number_format($control->actions_count) }} total</span></td>
                    <td><strong class="dg-cell-strong">{{ $control->updated_at?->format('d M Y') }}</strong><span class="dg-cell-note">{{ $control->updated_at?->format('H:i') }}</span></td>
                </tr>
            @endforeach
            </tbody></table></div>
            <div class="dg-register-footer"><span>Showing {{ number_format($controls->firstItem()) }}–{{ number_format($controls->lastItem()) }} of {{ number_format($controls->total()) }}</span><span>Scroll horizontally on smaller screens.</span></div>
            @if($controls->hasPages())<div class="dg-pagination">{{ $controls->links() }}</div>@endif
        @else
            <div class="dg-empty"><span>GOV</span><strong>No governance instruments match this scope</strong><p>Clear the filters or create the first controlled instrument. Do not record a policy as approved until its owner, steward, requirements, effective date and review date are verified.</p>@if($canManage)<a class="dg-btn dg-btn-primary" href="#governance-add" data-dg-open="governance-add">Create controlled draft</a>@endif</div>
        @endif
    </section>

    <section class="dg-panel dg-detail" id="governance-detail" aria-labelledby="governance-detail-title">
        @if($selectedControl)
            <div class="dg-detail-head"><div class="dg-detail-mark">{{ str($selectedControl->instrument_type)->substr(0, 3)->upper() }}</div><div><span class="dg-eyebrow-dark">Selected governance instrument</span><h2 id="governance-detail-title">{{ $selectedControl->control_code }} <small>Version {{ $selectedControl->version }}</small></h2><p>{{ $selectedControl->title }}</p></div><span class="dg-status {{ $tone($selectedControl->status) }}">{{ $statuses[$selectedControl->status] }}</span></div>
            <div class="dg-detail-actions"><a class="dg-btn dg-btn-primary" href="{{ route('budget.me.rebuild.data-governance.pdf', ['control_id' => $selectedControl->id, 'lifecycle' => $selectedControl->status === 'retired' ? 'all' : 'active']) }}">Control sheet PDF</a>@if($selectedControl->evidence)<a class="dg-btn dg-btn-secondary" href="{{ route('budget.me.rebuild.knowledge-repository', ['document_id' => $selectedControl->evidence->id]) }}">Open evidence</a>@endif @if($canManage && $selectedControl->isEditable())<a class="dg-btn dg-btn-secondary" href="#governance-edit" data-dg-open="governance-edit">Edit instrument</a>@endif @if($canManage && $selectedControl->status !== 'retired')<a class="dg-btn dg-btn-secondary" href="#governance-action" data-dg-open="governance-action">Add governance action</a>@endif</div>

            <div class="dg-detail-grid">
                <section><h3>Authority and accountability</h3><dl class="dg-metadata">
                    <div><dt>Domain</dt><dd>{{ $domains[$selectedControl->governance_domain] }}</dd></div><div><dt>Instrument type</dt><dd>{{ $instrumentTypes[$selectedControl->instrument_type] }}</dd></div>
                    <div><dt>Scope</dt><dd>{{ $scopeTypes[$selectedControl->scope_type] }}</dd></div><div><dt>Scope owner</dt><dd>{{ $selectedControl->portfolio?->name ?: $selectedControl->thinkTank?->name ?: 'ATTP enterprise' }}</dd></div>
                    <div><dt>Accountable owner</dt><dd>{{ $selectedControl->owner?->name ?: 'Not assigned' }}</dd></div><div><dt>Data steward</dt><dd>{{ $selectedControl->steward?->name ?: 'Not assigned' }}</dd></div>
                    <div><dt>Classification</dt><dd>{{ $classifications[$selectedControl->data_classification] }}</dd></div><div><dt>Risk rating</dt><dd>{{ $risks[$selectedControl->risk_rating] }}</dd></div>
                    <div><dt>Implementation</dt><dd>{{ $implementationStatuses[$selectedControl->implementation_status] }}</dd></div><div><dt>Lifecycle</dt><dd>{{ $statuses[$selectedControl->status] }}</dd></div>
                    <div><dt>Effective date</dt><dd>{{ $selectedControl->effective_date?->format('d M Y') ?: 'Not set' }}</dd></div><div><dt>Next review</dt><dd>{{ $selectedControl->next_review_date?->format('d M Y') ?: 'Not scheduled' }}</dd></div>
                </dl></section>
                <section><h3>Control definition</h3>@if($selectedControl->description)<div class="dg-prose"><strong>Purpose and scope</strong><p>{{ $selectedControl->description }}</p></div>@endif<div class="dg-prose requirements"><strong>Mandatory requirements</strong><p>{{ $selectedControl->requirements ?: 'Requirements have not yet been documented.' }}</p></div><div class="dg-evidence"><span>EV</span><div><strong>{{ $selectedControl->evidence?->title ?: 'No validated repository evidence linked' }}</strong><p>{{ $selectedControl->evidence_notes ?: 'Link a validated policy, standard, procedure or test record from the Knowledge and Evidence Repository.' }}</p></div>@if($selectedControl->evidence)<span class="dg-status {{ $tone($selectedControl->evidence->validation_status) }}">{{ str($selectedControl->evidence->validation_status)->headline() }}</span>@endif</div></section>
            </div>

            <section class="dg-action-queue"><div class="dg-section-head"><div><h3>Remediation and review action queue</h3><p>Every gap, exception, incident and scheduled review has an accountable owner and permanent closure record.</p></div>@if($canManage && $selectedControl->status !== 'retired')<a class="dg-btn dg-btn-small dg-btn-primary" href="#governance-action" data-dg-open="governance-action">Add action</a>@endif</div>
                @if($selectedControl->actions->isNotEmpty())<div class="dg-action-list">@foreach($selectedControl->actions as $action)<article class="{{ $action->isOverdue() ? 'overdue' : '' }}" data-action-id="{{ $action->id }}"><span class="dg-action-priority {{ $tone($action->priority) }}">{{ $actionPriorities[$action->priority] }}</span><div><div class="dg-action-title"><strong>{{ $action->title }}</strong><span class="dg-status {{ $tone($action->status) }}">{{ $actionStatuses[$action->status] }}</span></div><p>{{ $actionTypes[$action->action_type] }} · Owner: {{ $action->owner?->name ?: 'Unassigned' }} · Due: {{ $action->due_date?->format('d M Y') ?: 'Not scheduled' }}</p>@if($action->description)<small>{{ $action->description }}</small>@endif @if($action->resolution_notes)<div class="dg-resolution"><strong>Closure record</strong><p>{{ $action->resolution_notes }}</p><small>{{ $action->resolver?->name }} · {{ $action->resolved_at?->format('d M Y, H:i') }}</small></div>@endif</div>@if($canManage)<div class="dg-action-buttons">@if($action->isOpen())<button class="dg-link" type="button" data-action-edit data-url="{{ route('budget.me.rebuild.data-governance.actions.update', $action) }}" data-type="{{ $action->action_type }}" data-title="{{ $action->title }}" data-description="{{ $action->description }}" data-priority="{{ $action->priority }}" data-status="{{ $action->status }}" data-owner="{{ $action->owner_user_id }}" data-due="{{ $action->due_date?->format('Y-m-d') }}">Edit</button><button class="dg-link danger" type="button" data-action-resolve data-action-id="{{ $action->id }}" data-url="{{ route('budget.me.rebuild.data-governance.actions.resolve', $action) }}" data-title="{{ $action->title }}">Close</button>@else<form method="POST" action="{{ route('budget.me.rebuild.data-governance.actions.reopen', $action) }}" data-confirm="Reopen this governance action and remove its closure state?">@csrf<button class="dg-link" type="submit">Reopen</button></form>@endif</div>@endif</article>@endforeach</div>@else<div class="dg-empty dg-empty-compact"><span>ACT</span><strong>No governance actions recorded</strong><p>This instrument has no open remediation, exception or review tasks.</p></div>@endif
            </section>

            @if($canManage)<div class="dg-lifecycle"><div><strong>Controlled lifecycle actions</strong><p>Approval retires any earlier approved version of the same code. Retirement is blocked while open actions remain.</p></div><div class="dg-actions">
                @if($selectedControl->status === 'draft')<form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.submit-review', $selectedControl) }}" data-confirm="Submit this draft for governance approval review?">@csrf<button class="dg-btn dg-btn-primary" type="submit">Submit for review</button></form>@endif
                @if($selectedControl->status === 'under_review')<form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.approve', $selectedControl) }}" data-confirm="Approve this version as authoritative and retire any previous approved version?">@csrf<button class="dg-btn dg-btn-success" type="submit">Approve instrument</button></form>@endif
                @if(in_array($selectedControl->status, ['approved','retired'], true))<form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.new-version', $selectedControl) }}" data-confirm="Create a new draft major version while retaining this version?">@csrf<button class="dg-btn dg-btn-secondary" type="submit">Create new version</button></form>@endif
                @if($selectedControl->status !== 'retired')<form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.retire', $selectedControl) }}" data-confirm="Retire this instrument? Its versions, approval and action history will be preserved.">@csrf<button class="dg-btn dg-btn-danger" type="submit">Retire</button></form>@endif
            </div></div>@endif
        @else
            <div class="dg-empty"><span>SEL</span><strong>Select a governance instrument</strong><p>Choose a register row to inspect authority, accountability, requirements, evidence and remediation history.</p></div>
        @endif
    </section>

    @if($canManage)
        @php
            $formControl = $selectedControl;
            $controlFields = [
                'control_code' => old('control_code', $formControl?->control_code), 'title' => old('title', $formControl?->title),
                'governance_domain' => old('governance_domain', $formControl?->governance_domain), 'instrument_type' => old('instrument_type', $formControl?->instrument_type ?? 'control'),
                'version' => old('version', $formControl?->version ?? '1.0'), 'scope_type' => old('scope_type', $formControl?->scope_type ?? 'enterprise'),
                'portfolio_id' => old('portfolio_id', $formControl?->portfolio_id), 'think_tank_member_id' => old('think_tank_member_id', $formControl?->think_tank_member_id),
                'owner_user_id' => old('owner_user_id', $formControl?->owner_user_id), 'steward_user_id' => old('steward_user_id', $formControl?->steward_user_id),
                'data_classification' => old('data_classification', $formControl?->data_classification ?? 'internal'), 'risk_rating' => old('risk_rating', $formControl?->risk_rating ?? 'moderate'),
                'implementation_status' => old('implementation_status', $formControl?->implementation_status ?? 'not_started'), 'review_frequency' => old('review_frequency', $formControl?->review_frequency ?? 'annual'),
                'effective_date' => old('effective_date', $formControl?->effective_date?->format('Y-m-d')), 'next_review_date' => old('next_review_date', $formControl?->next_review_date?->format('Y-m-d')),
                'description' => old('description', $formControl?->description), 'requirements' => old('requirements', $formControl?->requirements),
                'evidence_notes' => old('evidence_notes', $formControl?->evidence_notes), 'evidence_repository_item_id' => old('evidence_repository_item_id', $formControl?->evidence_repository_item_id),
            ];
        @endphp
        <section class="dg-modal {{ $oldContext === 'control_create' ? 'is-open' : '' }}" id="governance-add" role="dialog" aria-modal="true" aria-labelledby="governance-add-title" data-dg-modal @if($oldContext === 'control_create') data-auto-open @endif><a class="dg-modal-backdrop" href="#" data-dg-close aria-label="Close"></a><div class="dg-modal-card"><header><div><span>Controlled governance intake</span><h2 id="governance-add-title">Create governance instrument</h2><p>Start as a draft. Approval is available only after accountability, requirements, effective date and review timing are complete.</p></div><a class="dg-modal-close" href="#" data-dg-close>×</a></header><form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.store') }}">@csrf<input type="hidden" name="form_context" value="control_create">@include('me.data-governance.partials.control-form', ['values' => $oldContext === 'control_create' ? $controlFields : []])<footer><a class="dg-btn dg-btn-secondary" href="#" data-dg-close>Cancel</a><button class="dg-btn dg-btn-primary" type="submit">Create controlled draft</button></footer></form></div></section>

        @if($selectedControl && $selectedControl->isEditable())<section class="dg-modal {{ $oldContext === 'control_update' ? 'is-open' : '' }}" id="governance-edit" role="dialog" aria-modal="true" aria-labelledby="governance-edit-title" data-dg-modal @if($oldContext === 'control_update') data-auto-open @endif><a class="dg-modal-backdrop" href="#" data-dg-close aria-label="Close"></a><div class="dg-modal-card"><header><div><span>Controlled draft maintenance</span><h2 id="governance-edit-title">Edit {{ $selectedControl->control_code }} version {{ $selectedControl->version }}</h2><p>Approved instruments cannot be edited; they are changed only by creating and approving a new version.</p></div><a class="dg-modal-close" href="#" data-dg-close>×</a></header><form method="POST" action="{{ route('budget.me.rebuild.data-governance.controls.update', $selectedControl) }}">@csrf @method('PUT')<input type="hidden" name="form_context" value="control_update">@include('me.data-governance.partials.control-form', ['values' => $controlFields])<footer><a class="dg-btn dg-btn-secondary" href="#" data-dg-close>Cancel</a><button class="dg-btn dg-btn-primary" type="submit">Save controlled draft</button></footer></form></div></section>@endif

        @if($selectedControl && $selectedControl->status !== 'retired')<section class="dg-modal {{ $oldContext === 'action_create' ? 'is-open' : '' }}" id="governance-action" role="dialog" aria-modal="true" aria-labelledby="governance-action-title" data-dg-modal @if($oldContext === 'action_create') data-auto-open @endif><a class="dg-modal-backdrop" href="#" data-dg-close></a><div class="dg-modal-card dg-modal-narrow"><header><div><span>Accountability queue</span><h2 id="governance-action-title">Add governance action</h2><p>Record a gap, remediation, review, exception follow-up or data incident against {{ $selectedControl->control_code }}.</p></div><a class="dg-modal-close" href="#" data-dg-close>×</a></header><form method="POST" action="{{ route('budget.me.rebuild.data-governance.actions.store', $selectedControl) }}">@csrf<input type="hidden" name="form_context" value="action_create">@include('me.data-governance.partials.action-form', ['prefix' => 'new-action'])<footer><a class="dg-btn dg-btn-secondary" href="#" data-dg-close>Cancel</a><button class="dg-btn dg-btn-primary" type="submit">Add governance action</button></footer></form></div></section>@endif

        <section class="dg-modal {{ $oldContext === 'action_update' && $oldAction ? 'is-open' : '' }}" id="governance-action-edit" role="dialog" aria-modal="true" aria-labelledby="governance-action-edit-title" data-dg-modal @if($oldContext === 'action_update' && $oldAction) data-auto-open @endif><a class="dg-modal-backdrop" href="#" data-dg-close></a><div class="dg-modal-card dg-modal-narrow"><header><div><span>Accountability queue</span><h2 id="governance-action-edit-title">Edit governance action</h2><p>Update ownership, due date, priority and current work state.</p></div><a class="dg-modal-close" href="#" data-dg-close>×</a></header><form method="POST" action="{{ $oldAction ? route('budget.me.rebuild.data-governance.actions.update', $oldAction) : '#' }}" data-action-edit-form>@csrf @method('PUT')<input type="hidden" name="form_context" value="action_update"><input type="hidden" name="action_id" value="{{ old('action_id') }}">@include('me.data-governance.partials.action-form', ['prefix' => 'edit-action', 'editing' => true])<footer><a class="dg-btn dg-btn-secondary" href="#" data-dg-close>Cancel</a><button class="dg-btn dg-btn-primary" type="submit">Save action</button></footer></form></div></section>

        <section class="dg-modal {{ $oldContext === 'action_resolve' && $oldAction ? 'is-open' : '' }}" id="governance-action-resolve" role="dialog" aria-modal="true" aria-labelledby="governance-action-resolve-title" data-dg-modal @if($oldContext === 'action_resolve' && $oldAction) data-auto-open @endif><a class="dg-modal-backdrop" href="#" data-dg-close></a><div class="dg-modal-card dg-modal-narrow"><header><div><span>Permanent closure record</span><h2 id="governance-action-resolve-title">Close governance action</h2><p data-resolve-copy>Record how this action was concluded.</p></div><a class="dg-modal-close" href="#" data-dg-close>×</a></header><form method="POST" action="{{ $oldAction ? route('budget.me.rebuild.data-governance.actions.resolve', $oldAction) : '#' }}" data-action-resolve-form>@csrf<input type="hidden" name="form_context" value="action_resolve"><input type="hidden" name="action_id" value="{{ old('action_id') }}"><div class="dg-modal-body"><div class="dg-form-grid"><div class="dg-field"><label for="resolution-status">Closure outcome *</label><select class="form-select" id="resolution-status" name="resolution_status" required><option value="resolved" @selected(old('resolution_status') === 'resolved')>Resolved</option><option value="risk_accepted" @selected(old('resolution_status') === 'risk_accepted')>Risk accepted</option><option value="cancelled" @selected(old('resolution_status') === 'cancelled')>Cancelled</option></select></div><div class="dg-field dg-field-full"><label for="resolution-notes">Resolution and evidence summary *</label><textarea class="form-control" id="resolution-notes" name="resolution_notes" rows="5" minlength="10" maxlength="5000" required placeholder="Explain the work completed, decision made, evidence reviewed and any residual risk.">{{ old('resolution_notes') }}</textarea></div></div></div><footer><a class="dg-btn dg-btn-secondary" href="#" data-dg-close>Cancel</a><button class="dg-btn dg-btn-danger" type="submit">Record closure</button></footer></form></div></section>
    @endif
</div>
@endsection

@push('scripts')
<script src="{{ asset('admin/assets/vendors/js/apexcharts.min.js') }}"></script>
<script>
(function () {
    const ready = function () {
        const body = document.body;
        const openModal = function (id) { const modal = document.getElementById(id); if (!modal) return; document.querySelectorAll('[data-dg-modal].is-open').forEach(item => item.classList.remove('is-open')); modal.classList.add('is-open'); body.classList.add('dg-modal-open'); setTimeout(() => modal.querySelector('input:not([type="hidden"]),select,textarea,button')?.focus(), 20); };
        const closeModal = function (modal) { modal?.classList.remove('is-open'); if (!document.querySelector('[data-dg-modal].is-open')) body.classList.remove('dg-modal-open'); };
        document.addEventListener('click', function (event) {
            const opener = event.target.closest('[data-dg-open]'); if (opener) { event.preventDefault(); openModal(opener.dataset.dgOpen); return; }
            const closer = event.target.closest('[data-dg-close]'); if (closer) { event.preventDefault(); closeModal(closer.closest('[data-dg-modal]')); return; }
            const row = event.target.closest('[data-dg-row]'); if (row && !event.target.closest('a,button,input,select,textarea,form')) { window.location.href = row.dataset.href; return; }
            const edit = event.target.closest('[data-action-edit]'); if (edit) { const form = document.querySelector('[data-action-edit-form]'); form.action = edit.dataset.url; form.querySelector('[name="action_id"]').value = edit.closest('article')?.dataset.actionId || edit.dataset.actionId || ''; form.querySelector('[name="action_type"]').value = edit.dataset.type; form.querySelector('[name="title"]').value = edit.dataset.title; form.querySelector('[name="description"]').value = edit.dataset.description || ''; form.querySelector('[name="priority"]').value = edit.dataset.priority; form.querySelector('[name="status"]').value = edit.dataset.status; form.querySelector('[name="owner_user_id"]').value = edit.dataset.owner || ''; form.querySelector('[name="due_date"]').value = edit.dataset.due || ''; openModal('governance-action-edit'); return; }
            const resolve = event.target.closest('[data-action-resolve]'); if (resolve) { const form = document.querySelector('[data-action-resolve-form]'); form.action = resolve.dataset.url; form.querySelector('[name="action_id"]').value = resolve.dataset.actionId || ''; document.querySelector('[data-resolve-copy]').textContent = 'Record the outcome for “' + resolve.dataset.title + '”. This entry remains in the audit history.'; openModal('governance-action-resolve'); }
        });
        document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(document.querySelector('[data-dg-modal].is-open')); });
        document.querySelectorAll('[data-dg-modal][data-auto-open]').forEach(modal => openModal(modal.id));
        if (window.location.hash === '#governance-add') openModal('governance-add');
        document.querySelectorAll('[data-confirm]').forEach(form => form.addEventListener('submit', function (event) { if (!window.confirm(this.dataset.confirm)) event.preventDefault(); }));
        document.querySelectorAll('[data-scope-select]').forEach(select => { const sync = function () { const form = select.closest('form'); form.querySelectorAll('[data-scope-field]').forEach(field => field.hidden = !field.dataset.scopeField.split(',').includes(select.value)); }; select.addEventListener('change', sync); sync(); });

        const lifecycle = @json($charts['lifecycle']); const domains = @json($charts['domain']); const risk = @json($charts['risk']);
        const baseUrl = @json(route('budget.me.rebuild.data-governance')); const baseFilters = @json($preservedFilters);
        const openFiltered = extra => { const query = new URLSearchParams({...baseFilters, ...extra}); window.location.href = baseUrl + '?' + query.toString(); };
        const render = function (selector, options) { const target = document.querySelector(selector); if (!target) return; if (typeof window.ApexCharts !== 'function') { target.innerHTML = '<div class="dg-chart-empty"><strong>Chart unavailable</strong><span>The register and exports remain available.</span></div>'; return; } new window.ApexCharts(target, options).render(); };
        const base = {chart:{fontFamily:'Inter, Arial, sans-serif',foreColor:'#657980',toolbar:{show:false},animations:{speed:380}},grid:{borderColor:'#e4ecee',strokeDashArray:3},tooltip:{theme:'light'},noData:{text:'No governance data in this scope'}};
        render('#dg-lifecycle-chart',{...base,chart:{...base.chart,type:'donut',height:300,events:{dataPointSelection:(_e,_c,s)=>{const item=lifecycle[s.dataPointIndex];if(item)openFiltered({status:item.key,lifecycle:'all'});}}},series:lifecycle.map(i=>i.count),labels:lifecycle.map(i=>i.label),colors:lifecycle.map(i=>i.color),stroke:{colors:['#fff'],width:3},dataLabels:{enabled:false},legend:{position:'bottom',fontSize:'10px'},plotOptions:{pie:{donut:{size:'66%',labels:{show:true,total:{show:true,label:'Instruments',formatter:()=>lifecycle.reduce((sum,i)=>sum+i.count,0)}}}}}});
        render('#dg-domain-chart',{...base,chart:{...base.chart,type:'bar',height:300,events:{dataPointSelection:(_e,_c,s)=>{const item=domains[s.dataPointIndex];if(item)openFiltered({domain:item.key});}}},series:[{name:'Registered',data:domains.map(i=>i.controls)},{name:'Implemented',data:domains.map(i=>i.implemented)}],colors:['#8fb7c2','#187459'],plotOptions:{bar:{horizontal:true,borderRadius:3,barHeight:'58%'}},xaxis:{categories:domains.map(i=>i.label),min:0,forceNiceScale:true,labels:{formatter:v=>Math.round(v)}},yaxis:{labels:{maxWidth:180,style:{fontSize:'9px'}}},dataLabels:{enabled:false},legend:{position:'bottom',fontSize:'10px'}});
        render('#dg-risk-chart',{...base,chart:{...base.chart,type:'bar',height:300,events:{dataPointSelection:(_e,_c,s)=>{const item=risk[s.dataPointIndex];if(item)openFiltered({risk:item.key});}}},series:[{name:'Instruments',data:risk.map(i=>i.count)}],colors:risk.map(i=>i.color),plotOptions:{bar:{distributed:true,borderRadius:4,columnWidth:'52%'}},xaxis:{categories:risk.map(i=>i.label)},yaxis:{min:0,forceNiceScale:true,labels:{formatter:v=>Math.round(v)}},dataLabels:{enabled:true,formatter:v=>Math.round(v)},legend:{show:false}});
    };
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', ready, {once:true}); else ready();
})();
</script>
@endpush
